[package]
name = "graph-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-iter = "1.2.0"
priority-queue = "1.3.2"
rand = "0.8.5"
rayon = "1.8.0"
az-discrete-opt = { version = "0.1.0", path = "../az-discrete-opt" }
itertools = "0.11.0"

[dev-dependencies]
criterion = "0.5.1"
dfdx = { version = "0.13.0", default-features = false, features = ["std", "fast-alloc", "cuda", "cudnn"]}
priority-queue = "1.3.2"
rand = "0.8.5"
rayon = "1.7.0"

[[bench]]
name = "r44_17_search_tree_with_trivial_predictions"
harness = false
